### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by PrajaktaSathe** [ankit-kmar/Digi-Art#55]
I can make folders in this repository. 
For example - a 'festivals' folder for illustrations related to it.
Please let me know if I can do that!

**Comment by ankit-kmar** [comment]
> I can make folders in this repository. For example - a 'festivals' folder for illustrations related to it. Please let me know if I can do that!

not needed, just add the illustrations. I'll look into it.

**Comment by PrajaktaSathe** [comment]
Ok!
